# Generated by Django 4.2.6 on 2024-01-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_thread_delete_personalmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='channel_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
