# Generated by Django 4.2.6 on 2024-01-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_thread_channel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='channel_number',
        ),
    ]
