# Generated by Django 4.2.6 on 2024-01-18 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_thread_channel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
