# Generated by Django 4.2.6 on 2024-01-18 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_thread_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
    ]
