# Generated by Django 4.2.6 on 2024-01-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_thread_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
