# Generated by Django 5.0.1 on 2024-01-22 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_group_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='unique_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
